---
- name: Install nginx
  yum: name=nginx state=present

- name: Disable default configuration
  command: mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.disabled creates=/etc/nginx/conf.d/default.disabled
  notify: restart nginx

- name: Copy nginx configuration
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- service: name=nginx enabled=yes state=started

- name: insert firewalld rule for web server 80
  firewalld: port=80/tcp permanent=true state=enabled immediate=yes

- name: insert firewalld rule for web server 443
  firewalld: port=443/tcp permanent=true state=enabled immediate=yes
