---
- name: Dev server
  hosts: 108.61.174.104
  become: yes

  vars:
    ntp_enabled: true
    ntp_timezone: UTC
    composer_home_owner: nginx
    composer_home_group: nginx
    composer_keep_updated: true

  roles:
    - geerlingguy.repo-epel
    - geerlingguy.repo-remi
    - geerlingguy.ntp
    - geerlingguy.composer
    - common
    - php-fpm
    - nginx
    - mariadb

#letsencrypt certonly --webroot --rsa-key-size 4096 -w /www/prod/web/ -d sonurai.com -d www.sonurai.com -d next.sonurai.com -w /www/work/web/ -d work.sonurai.com
# 08 00 * * * /usr/bin/wget -q -O - http://108.61.174.104/bingwallpapers/update
# 09 00 * * * /usr/bin/letsencrypt renew && systemctl restart nginx
