---
# - name: Disable SELinux
#   selinux: state=disabled

# - name: disable selinux
#   command: /sbin/setenforce 0

- name: Copy the NGINX repository definition
  copy: src=nginx.repo dest=/etc/yum.repos.d/

- name: Copy the MariaDB repository definition
  copy: src=mariadb.repo dest=/etc/yum.repos.d/

- name: Create the GPG key for NGINX
  copy: src=RPM-GPG-KEY-NGINX dest=/etc/pki/rpm-gpg

- name: Create the GPG key for MARIADB
  copy: src=RPM-GPG-KEY-MARIADB dest=/etc/pki/rpm-gpg

- name: Install common file
  yum: name={{ item }} enablerepo=remi,remi-php70 state=present
  with_items:
    - git
    - htop
    - letsencrypt
    - tree
    - unzip
    - wget

- git: repo=https://github.com/sonu27/sonurai.com.git dest=/www/prod update=no
- composer: command=install working_dir=/www/prod no_dev=no prefer_dist=yes optimize_autoloader=yes
#chgrp nginx /var/lib/php/*
